export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";
export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO_STATUS = "TOGGLE_TODO_STATUS";
export const TOGGLE_MODAL_OPEN = "TOGGLE_MODAL_OPEN";
export const TOGGLE_MODAL_CLOSE = "TOGGLE_MODAL_CLOSE";
